@baseUrl = http://localhost:{{$dotenv LOCAL_PORT}}
# @baseUrl = https://server.alexandre-richard.fr

### * Route GET /
GET {{baseUrl}}

### * Route GET Ajouer 1 au compteur de visite
POST {{baseUrl}}/visit/counter/add HTTP/1.1
Content-Type: application/json

{
    "target": "testing"
}

### * Envoie de mail
POST {{baseUrl}}/contact HTTP/1.1
Content-Type: application/json

{
"contactFormMail": "alex@gmail.com",
"contactFormMessage": "ENCORE UN TEST",
"contactFormName": "Alexandre",
"contactFormSubject": "TEST"
}